# Generated by Django 4.2.16 on 2025-01-16 14:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 16, 17, 23, 30, 958369)),
        ),
        migrations.AlterField(
            model_name='sales',
            name='data_of_sale',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 16, 17, 23, 30, 958369)),
        ),
    ]
